remote_theme: coursweb/jk-theme
title: Cours Git
description: Un cours d'introduction à Git et GitHub.
lang: fr-FR
chapters:
 - title: Cours-web
   url: https://cours-web.ch/
 - title: Git
   url: https://cours-web.ch/git/
# Footer content
# Content is split in three columns.   
footer_col_1: <ul class="contact-list">
  <li>Eracom, Lausanne</li>
  <li>2017–2021</li></ul>
footer_col_2: <ul class="social-media-list"><li><a href="https://github.com/coursweb/git">Lien Github</a></li></ul>