remote_theme: coursweb/jk-theme
title: Cours Git
description: Un cours d'introduction à Git et GitHub.
lang: fr-FR
chapters:
 - title: Cours-web
   url: https://cours-web.ch/
 - title: Git
   url: https://cours-web.ch/git/
